/* Word lists by grade level.
   Each entry: [word, sentence]  — the sentence is read aloud after the word,
   the way a real spelling test works: "word ... sentence ... word." */

const WORD_LISTS = {
  g1: {
    label: "Grade 1",
    blurb: "Short words and sight words",
    words: [
      ["cat", "The cat sat on my gym bag."],
      ["dog", "My dog runs beside me."],
      ["sun", "The sun is warm today."],
      ["run", "I run fast down the mat."],
      ["big", "That is a big jump."],
      ["red", "She wore a red bow."],
      ["jump", "Watch me jump up high."],
      ["stop", "We stop when the coach claps."],
      ["play", "We play in the gym."],
      ["like", "I like doing cartwheels."],
      ["look", "Look at my handstand."],
      ["ball", "The ball rolled away."],
      ["hand", "Put your hand on the mat."],
      ["hop", "I can hop on one foot."],
      ["mat", "Roll out the blue mat."],
      ["flip", "She did a flip in the air."],
      ["bed", "I made my bed today."],
      ["fun", "Gymnastics is so much fun."],
      ["cup", "I filled my cup with water."],
      ["hat", "My hat blew off outside."],
      ["pig", "The pig rolled in the mud."],
      ["sit", "Please sit on the bench."],
      ["tap", "Tap your toes to the beat."],
      ["win", "Our team can win today."],
      ["top", "I climbed to the top."],
      ["mom", "My mom cheers the loudest."],
      ["dad", "My dad filmed my routine."],
      ["girl", "That girl is on my squad."],
      ["boy", "The boy waved at us."],
      ["yes", "Yes, I want to try again."],
      ["can", "I can do it myself."],
      ["get", "Let me get my water bottle."],
      ["has", "She has a new leotard."],
      ["see", "I see the finish line."],
      ["was", "It was a great practice."],
      ["went", "We went to the meet."],
      ["best", "You did your best."],
      ["fast", "She is very fast."],
      ["five", "Give me a high five."],
      ["star", "I got a gold star."]
    ]
  },

  g2: {
    label: "Grade 2",
    blurb: "Blends, digraphs, and silent e",
    words: [
      ["about", "Tell me about your routine."],
      ["after", "We stretch after practice."],
      ["again", "Let's try that again."],
      ["because", "I smiled because I landed it."],
      ["before", "Warm up before you tumble."],
      ["could", "I could hold the handstand."],
      ["every", "Every gymnast gets a turn."],
      ["first", "She went first on the beam."],
      ["found", "I found my missing sock."],
      ["going", "We are going to the gym."],
      ["happy", "I felt happy on the podium."],
      ["house", "My friend lives in that house."],
      ["jumped", "She jumped higher than ever."],
      ["kind", "Be kind to your teammates."],
      ["laugh", "We laugh a lot at practice."],
      ["little", "Just a little more stretch."],
      ["made", "I made the team."],
      ["might", "It might rain later."],
      ["night", "The meet is on Friday night."],
      ["once", "We practiced it once more."],
      ["only", "Only two turns are left."],
      ["other", "Use your other foot."],
      ["people", "So many people were watching."],
      ["place", "I got second place."],
      ["right", "Lift your right leg."],
      ["said", "The coach said good job."],
      ["school", "We have gym at school."],
      ["should", "You should point your toes."],
      ["sister", "My sister came to watch."],
      ["small", "The gym has a small trampoline."],
      ["sound", "I love the sound of cheering."],
      ["still", "Hold very still."],
      ["their", "Their team wore purple."],
      ["there", "Stand over there."],
      ["these", "These are my favorite shoes."],
      ["thing", "That was the coolest thing."],
      ["think", "I think I can do it."],
      ["three", "I did three cartwheels."],
      ["under", "Roll under the bar."],
      ["water", "Drink some water now."],
      ["where", "Where did you put the chalk?"],
      ["which", "Which bow should I wear?"],
      ["would", "Would you spot me, please?"],
      ["write", "I will write my name on it."],
      ["your", "Point your toes."]
    ]
  },

  g3: {
    label: "Grade 3",
    blurb: "Longer words with tricky vowel teams",
    words: [
      ["address", "I wrote my address on the form."],
      ["animal", "A cheetah is a fast animal."],
      ["answer", "Raise your hand to answer."],
      ["balance", "Keep your balance on the beam."],
      ["beautiful", "That was a beautiful routine."],
      ["believe", "I believe in you."],
      ["between", "Stand between the two mats."],
      ["breakfast", "Eat breakfast before the meet."],
      ["bridge", "She held the bridge for ten seconds."],
      ["brother", "My brother came to cheer."],
      ["careful", "Be careful on the landing."],
      ["catch", "I will catch you."],
      ["certain", "I am certain we practiced this."],
      ["change", "Change into your leotard."],
      ["circle", "We sat in a circle to stretch."],
      ["clothes", "Pack your clothes in the bag."],
      ["coach", "My coach taught me a new skill."],
      ["complete", "Complete the whole routine."],
      ["corner", "Start in the corner of the floor."],
      ["country", "Gymnasts came from every country."],
      ["decide", "You decide which event is first."],
      ["different", "Every gymnast is different."],
      ["double", "She did a double turn."],
      ["during", "Stay quiet during her routine."],
      ["early", "We arrived early to warm up."],
      ["enough", "That is high enough."],
      ["exercise", "Exercise makes you strong."],
      ["famous", "She is a famous gymnast."],
      ["favorite", "The beam is my favorite event."],
      ["finish", "Finish with a big smile."],
      ["follow", "Follow me across the floor."],
      ["friendly", "Our squad is very friendly."],
      ["gymnast", "The gymnast saluted the judges."],
      ["height", "Look at the height of that jump."],
      ["however", "I was nervous, however I did it."],
      ["important", "Landing safely is important."],
      ["island", "We flew to an island for the meet."],
      ["listen", "Listen for the music."],
      ["medal", "She won a gold medal."],
      ["minute", "You have one minute left."],
      ["mountain", "The gym is near a mountain."],
      ["notice", "Did you notice her form?"],
      ["perfect", "That landing was perfect."],
      ["practice", "Practice makes you better."],
      ["probably", "We will probably win."],
      ["question", "I have a question for the coach."],
      ["ribbon", "She twirled the pink ribbon."],
      ["straight", "Keep your legs straight."],
      ["stretch", "Stretch before you tumble."],
      ["surprise", "The trophy was a surprise."]
    ]
  },

  g4: {
    label: "Grade 4",
    blurb: "Multi-syllable words and prefixes",
    words: [
      ["achieve", "You can achieve your goal."],
      ["adventure", "The trip was a big adventure."],
      ["ancient", "Gymnastics is an ancient sport."],
      ["athlete", "Every athlete warmed up."],
      ["attention", "Pay attention to the coach."],
      ["audience", "The audience clapped loudly."],
      ["average", "Her average score was high."],
      ["awkward", "The first try felt awkward."],
      ["calendar", "The meet is on the calendar."],
      ["celebrate", "Let's celebrate your medal."],
      ["champion", "She is the state champion."],
      ["character", "Good sportsmanship shows character."],
      ["comfortable", "These shoes are comfortable."],
      ["community", "Our gym is a whole community."],
      ["competition", "The competition starts at noon."],
      ["confident", "Walk in feeling confident."],
      ["courage", "It takes courage to try a flip."],
      ["describe", "Describe your favorite skill."],
      ["develop", "You will develop more strength."],
      ["difficult", "That skill is difficult."],
      ["discover", "You might discover a new talent."],
      ["effort", "Great effort out there."],
      ["elegant", "Her arms looked elegant."],
      ["energy", "Cheerleaders have so much energy."],
      ["environment", "The gym is a safe environment."],
      ["excellent", "That was an excellent landing."],
      ["experience", "Meets give you experience."],
      ["familiar", "This routine feels familiar."],
      ["flexible", "Stretching makes you flexible."],
      ["gorgeous", "Your new leotard is gorgeous."],
      ["gradually", "Gradually lift your leg higher."],
      ["gymnasium", "The gymnasium was packed."],
      ["imagine", "Imagine landing it perfectly."],
      ["journey", "Learning a skill is a journey."],
      ["muscle", "You need muscle for the bars."],
      ["natural", "She is a natural on the beam."],
      ["opposite", "Turn in the opposite direction."],
      ["patience", "Learning takes patience."],
      ["physical", "Gymnastics is very physical."],
      ["rhythm", "Cheer needs good rhythm."],
      ["routine", "I memorized my whole routine."],
      ["schedule", "Check the practice schedule."],
      ["separate", "The teams sat in separate rows."],
      ["strength", "Push-ups build strength."],
      ["victory", "The victory felt amazing."]
    ]
  },

  g5: {
    label: "Grade 5",
    blurb: "Challenge words for strong spellers",
    words: [
      ["accomplish", "You can accomplish anything."],
      ["acrobatic", "She did an acrobatic leap."],
      ["appreciate", "I appreciate your hard work."],
      ["athletic", "He is very athletic."],
      ["brilliant", "That was a brilliant routine."],
      ["cartwheel", "I can do a one-handed cartwheel."],
      ["choreography", "The choreography was creative."],
      ["committee", "The committee chose the winners."],
      ["competitive", "She is very competitive."],
      ["concentrate", "Concentrate on the landing."],
      ["confidence", "Her confidence is growing."],
      ["courageous", "That was a courageous try."],
      ["definitely", "I definitely want to compete."],
      ["determination", "Her determination paid off."],
      ["disciplined", "Great gymnasts are disciplined."],
      ["dramatic", "The ending was dramatic."],
      ["endurance", "Cheer takes endurance."],
      ["enthusiasm", "She cheered with enthusiasm."],
      ["equipment", "Put the equipment away."],
      ["exhausted", "We were exhausted after practice."],
      ["extraordinary", "That vault was extraordinary."],
      ["gracefully", "She landed gracefully."],
      ["gymnastics", "Gymnastics is my favorite sport."],
      ["immediately", "Chalk your hands immediately."],
      ["independent", "She is an independent learner."],
      ["magnificent", "The floor routine was magnificent."],
      ["necessary", "A spotter is necessary."],
      ["opportunity", "This is a great opportunity."],
      ["perseverance", "Perseverance wins medals."],
      ["precision", "Her timing had real precision."],
      ["rehearsal", "We had one last rehearsal."],
      ["responsible", "Be responsible with the mats."],
      ["significant", "She made significant progress."],
      ["spectacular", "That dismount was spectacular."],
      ["symmetry", "The pyramid had perfect symmetry."],
      ["technique", "Work on your technique."],
      ["tremendous", "You showed tremendous focus."],
      ["triumphant", "She gave a triumphant wave."],
      ["unbelievable", "That score was unbelievable."],
      ["vigorous", "We did a vigorous warm-up."]
    ]
  },

  bonus: {
    label: "Gym & Cheer Words",
    blurb: "All the words from her sport",
    words: [
      ["arabesque", "She held a beautiful arabesque."],
      ["backflip", "He landed the backflip."],
      ["beam", "The balance beam is four inches wide."],
      ["bars", "She swings on the uneven bars."],
      ["bow", "My bow matches my uniform."],
      ["cartwheel", "Show me your best cartwheel."],
      ["chalk", "Put chalk on your hands."],
      ["cheer", "We cheer for our team."],
      ["dismount", "Stick the dismount."],
      ["floor", "The floor routine has music."],
      ["handspring", "She did a back handspring."],
      ["handstand", "Hold the handstand steady."],
      ["herkie", "A herkie is a cheer jump."],
      ["kick", "Kick your leg up high."],
      ["landing", "The landing was solid."],
      ["leap", "She took a giant leap."],
      ["leotard", "My leotard is sparkly."],
      ["megaphone", "She shouted into the megaphone."],
      ["pike", "Squeeze your legs in the pike."],
      ["pompom", "Shake your pompom high."],
      ["pyramid", "Our pyramid held steady."],
      ["salute", "Salute the judges when you finish."],
      ["somersault", "I rolled into a somersault."],
      ["split", "She can do a full split."],
      ["spotter", "The spotter kept her safe."],
      ["squad", "Our squad practices Tuesdays."],
      ["stunt", "That stunt needs three people."],
      ["trampoline", "We bounced on the trampoline."],
      ["tuck", "Pull your knees into a tuck."],
      ["tumble", "She loves to tumble."],
      ["vault", "She ran fast at the vault."],
      ["stretch", "Stretch your arms overhead."]
    ]
  }
};

const GRADE_ORDER = ["g1", "g2", "g3", "g4", "g5", "bonus"];
